export const NEGOTIATION_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  IN_PROGRESS: 'IN_PROGRESS',
  AGREEMENT: 'AGREEMENT',
  REJECTED: 'REJECTED',
  DEADLOCK: 'DEADLOCK',
  COMPLETED: 'COMPLETED',
};

export const DECISION_TYPE = {
  ACCEPT: 'ACCEPT',
  REJECT: 'REJECT',
  COUNTEROFFER: 'COUNTEROFFER',
  COUNTER: 'COUNTEROFFER',
};

export const CONCESSION_DIRECTION = {
  INCREASE: 'INCREASE',
  DECREASE: 'DECREASE',
  NO_CHANGE: 'NO_CHANGE',
};

export const NEGOTIATION_MODE = {
  SIMULATION: 'SIMULATION', // AI vs AI
  PRACTICE: 'PRACTICE',     // Human vs AI
};

export const STANCE_TYPE = {
  FIRM: 'Firm',
  FLEXIBLE: 'Flexible',
  MODERATE: 'Moderate',
  YIELDING: 'Yielding',
  STUBBORN: 'Stubborn',
};
